### ISSUE TITLE
./extract-files.sh

### ISSUE THREAD

**Issue by Steffov** [Exynos7580/android_device_samsung_s5neoltexx#3]
After starting ./extract-files.sh it runs very well until the pull of "gps.universal7580.so". 
`adb: error: remote object '/system/lib/hw/gps.universal7580.so' does not exist`
Due to this the whole script stopps. Is there any solution?

I'm on 6.0.1 stock rom (G903FXXU1BPF1_G903FOXA1BPF2_DBT) and try to prepair all to build CM 13.

Device: 903F

**Comment by david-brauer** [comment]
This was first made for Android 5.1.1
So I don't know if it will work for 6.0.1
Anyway I don't think that someone is working on this repository anymore

**Comment by Incineroar** [comment]
The comment at the bottom of the readme.md states that it was made for building CM13, which is based on Android 6.0.1, so it should work. I've been keeping my eye on this repository, but I don't know if anyone has actually built this, or if there's any built versions anywhere.

I was considering asking the authors, but I've been fairly occupied as of late to be able to ask.
